# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: TREC 2023 Tip-of-the-Tongue (ToT) Track
email: bmitra@microsoft.com
description: >- # this means to ignore newlines until "baseurl:"
  The Tip-of-the-Tongue (ToT) Track focuses on the known-item identification
  task where the searcher has previously experienced or consumed the item
  (e.g., a movie) but cannot recall a reliable identifier (i.e., "It's on the
  tip of my tongue…"). Unlike traditional ad-hoc keyword-based search, these
  information requests tend to be natural-language, verbose, and complex
  containing a wide variety of search strategies such as multi-hop reasoning,
  and frequently express uncertainty and suffer from false memories.
baseurl: "/site" # the subpath of your site, e.g. /blog
url: "https://trec-tot.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: UnderdogGeek
github_username:  bmitra-msft

# Build settings
theme: cayman
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
